language: node_js
node_js:
  - "12"
  - "13"
  - "14"
  - "15"
cache:
  directories:
    - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=6b737647c19540b99ebe2e3158b09f1e5d799ae6c2d5a49a236d922050a49e11
before_install:
  - npm i -g npm@latest
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
